#!/usr/bin/env python3
"""Generate a PLACEHOLDER model version so the pipeline can run end to end.

    python scripts/bootstrap_dev_model.py

The registry needs a complete `models/<version>/{best.pt,metadata.json,
labels.json}` before anything will resolve, and until the real training run
produces one there is nothing to point at. This writes a structurally valid
version with a **randomly initialised** head and backbone.

READ THIS BEFORE USING THE OUTPUT
---------------------------------
The weights are random. Every prediction is noise. This exists so that the
upload -> queue -> worker -> Firestore -> poll path can be exercised and the
frontend can be developed against real response shapes; it is not a model.

Three things keep it from being mistaken for one:

  * the version is named `v0-dev-untrained-*`
  * `metadata.json` carries `"untrained": true` and a `caveat`
  * `field_covered_classes` is empty, so every verdict is flagged as having
    no field validation behind it

Replace it with a real version the moment you have one:

    python scripts/register_model.py <artifacts-dir> --version v1-... --activate
    rm -rf models/v0-dev-untrained-*

`--threshold 0` is available for frontend work: with random weights the top
confidence sits near 1/38, so at the honest 0.95 threshold every diagnosis
comes back `uncertain` and the `completed` UI path never renders.
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import date
from pathlib import Path

# Make `app` importable when run from backend/ or backend/scripts/, and the
# repo root importable for data.py.
BACKEND_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BACKEND_DIR))

from app.config import get_settings  # noqa: E402


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--version",
        default=f"v0-dev-untrained-{date.today():%Y%m%d}",
        help="Version directory name",
    )
    ap.add_argument("--architecture", default="mobilenet_v2")
    ap.add_argument(
        "--threshold",
        type=float,
        default=0.95,
        help="Confidence threshold. 0 makes every verdict 'completed' (UI work).",
    )
    ap.add_argument("--force", action="store_true", help="Overwrite an existing dir")
    args = ap.parse_args()

    settings = get_settings()
    sys.path.insert(0, str(Path(settings.ml_repo_root).resolve()))

    import torch  # noqa: E402  (imported late: it is a ~2s import)

    from data import (  # noqa: E402
        DEFAULT_CENTER_CROP,
        DEFAULT_RESIZE,
        IMAGENET_MEAN,
        IMAGENET_STD,
        PLANTVILLAGE_CLASSES,
        build_label_map,
    )
    from predict import _build_backbone  # noqa: E402

    dest = Path(settings.model_registry_dir) / args.version
    if dest.exists() and not args.force:
        print(f"error: {dest} already exists; pass --force", file=sys.stderr)
        return 1
    dest.mkdir(parents=True, exist_ok=True)

    classes = list(PLANTVILLAGE_CLASSES)
    model = _build_backbone(args.architecture, len(classes))
    torch.save(model.state_dict(), dest / "best.pt")

    metadata = {
        "model_name": "agrivert-dev-placeholder",
        "architecture": args.architecture,
        "num_classes": len(classes),
        "classes": classes,
        "best_epoch": None,
        # Empty on purpose: an untrained model has no field validation behind
        # any class, so every verdict should be flagged.
        "field_covered_classes": [],
        "preprocessing": {
            "resize": DEFAULT_RESIZE,
            "center_crop": DEFAULT_CENTER_CROP,
            "normalize": {"mean": list(IMAGENET_MEAN), "std": list(IMAGENET_STD)},
        },
        "calibration": {
            "temperature": 1.0,
            "recommended_confidence_threshold": args.threshold,
        },
        # No metrics rather than zeroed metrics: a 0.0 accuracy would render
        # in the admin UI as a measured result.
        "metrics": {},
        "untrained": True,
        "caveat": (
            "PLACEHOLDER. Randomly initialised weights, never trained. Every "
            "prediction is noise. Generated by scripts/bootstrap_dev_model.py "
            "so the serving pipeline can run before a real checkpoint exists."
        ),
    }
    (dest / "metadata.json").write_text(json.dumps(metadata, indent=2) + "\n")
    (dest / "labels.json").write_text(
        json.dumps(build_label_map(classes), indent=2) + "\n"
    )

    print(f"wrote placeholder model version {args.version} to {dest}")
    print(f"  architecture     {args.architecture}")
    print(f"  classes          {len(classes)}")
    print(f"  threshold        {args.threshold}")
    print(
        "\nThis model is UNTRAINED and its predictions are meaningless.\n"
        "It is the only version on disk, so the registry will resolve it "
        "without a Firestore record.\n"
        "Replace it with scripts/register_model.py as soon as you have real "
        "weights."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
